/**
 * @file converseai_providers.js
 * @author scott@converse.ai
 *
 * Generated by the converse-cli tool for use with the Converse AI
 * Plugins SDK. https://developers.converse.ai/
 */

'use strict';

const Status = require('@converseai/plugins-sdk').Status;
const RegistrationDataResponse = require('@converseai/plugins-sdk').Payloads.RegistrationDataResponse;

var onProviderRegister = function(app, body) {

  var response = new RegistrationDataResponse();

  response.setRegistrationData(body.payload.registrationData);

  app.send(Status.SUCCESS, response);
}

var onProviderUnregister = function(app, body) {

  app.send(Status.SUCCESS);
}

module.exports = {
  onProviderRegister: onProviderRegister,
  onProviderUnregister: onProviderUnregister
}
